main: de.polygondev.community.Main
name: Community
version: 1.0
author: PolygonDEV 

commands:
  spawneffect:
    description: Spawn Effect
  stage:
    description: oeffne die buehnen GUI
  killeffects:
    description: kills all effects